# Generated by Django 3.2.7 on 2021-09-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materadmin", "0002_task"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="level",),
        migrations.AddField(
            model_name="developer",
            name="level",
            field=models.CharField(
                choices=[
                    ("junior", "Junior"),
                    ("senior", "Senior"),
                    ("teamlead", "Team Lead"),
                ],
                default="senior",
                max_length=8,
            ),
        ),
    ]
